name: "Tests"

on:
  pull_request:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  fail-fast: true

permissions:
  contents: read

jobs:
  test:
    name: "Run Python Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        continue-on-error: true

      - name: Install dependencies
        run: pip install -r requirements.txt
        continue-on-error: true

      - name: Run BDD tests
        run: python tests/bdd-unittests.py
        continue-on-error: true

      - name: Run TDD tests
        run: python tests/tdd-unittests.py
        continue-on-error: true
